package com.toolie.back_end.config;

import com.toolie.back_end.usuario.Usuario;
import com.toolie.back_end.usuario.UsuarioRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Arrays;
import java.util.List;

@Configuration
public class DevelopmentConfig {

    @Bean
    public CommandLineRunner dataLoader(UsuarioRepository usuarioRepository) {
        return args -> {
            List<Usuario> usuarios = Arrays.asList(
                    new Usuario("Jorge", "jorge@gmail.com"),
                    new Usuario("Maria", "maria@gmail.com"),
                    new Usuario("Pedro", "pedro@gmail.com"),
                    new Usuario("Ana", "ana@gmail.com"),
                    new Usuario("Luis", "luis@gmail.com"),
                    new Usuario("Carlos", "carlos@gmail.com"),
                    new Usuario("Lucia", "lucia@gmail.com"),
                    new Usuario("Fernando", "fernando@gmail.com"),
                    new Usuario("Elena", "elena@gmail.com"),
                    new Usuario("Diego", "diego@gmail.com"),
                    new Usuario("Patricia", "patricia@gmail.com"),
                    new Usuario("Raul", "raul@gmail.com"),
                    new Usuario("Sofia", "sofia@gmail.com"),
                    new Usuario("Miguel", "miguel@gmail.com"),
                    new Usuario("Laura", "laura@gmail.com"),
                    new Usuario("Andres", "andres@gmail.com"),
                    new Usuario("Isabel", "isabel@gmail.com"),
                    new Usuario("Roberto", "roberto@gmail.com"),
                    new Usuario("Teresa", "teresa@gmail.com"),
                    new Usuario("Victor", "victor@gmail.com"),
                    new Usuario("Sara", "sara@gmail.com"),
                    new Usuario("Tomas", "tomas@gmail.com"),
                    new Usuario("Raquel", "raquel@gmail.com"),
                    new Usuario("Julian", "julian@gmail.com"),
                    new Usuario("Gabriela", "gabriela@gmail.com"),
                    new Usuario("Alberto", "alberto@gmail.com"),
                    new Usuario("Claudia", "claudia@gmail.com"),
                    new Usuario("Fernando", "fernando2@gmail.com"),
                    new Usuario("Natalia", "natalia@gmail.com"),
                    new Usuario("Pablo", "pablo@gmail.com"),
                    new Usuario("Cristina", "cristina@gmail.com"),
                    new Usuario("Esteban", "esteban@gmail.com"),
                    new Usuario("Marina", "marina@gmail.com"),
                    new Usuario("Javier", "javier@gmail.com"),
                    new Usuario("Marta", "marta@gmail.com"),
                    new Usuario("Rafael", "rafael@gmail.com"),
                    new Usuario("Ines", "ines@gmail.com"),
                    new Usuario("Carmen", "carmen@gmail.com"),
                    new Usuario("Luis", "luis2@gmail.com"),
                    new Usuario("Felipe", "felipe@gmail.com"),
                    new Usuario("Veronica", "veronica@gmail.com"),
                    new Usuario("Adriana", "adriana@gmail.com"),
                    new Usuario("Benito", "benito@gmail.com"),
                    new Usuario("Clara", "clara@gmail.com"),
                    new Usuario("Daniel", "daniel@gmail.com"),
                    new Usuario("Eva", "eva@gmail.com"),
                    new Usuario("Felicia", "felicia@gmail.com"),
                    new Usuario("Gonzalo", "gonzalo@gmail.com"),
                    new Usuario("Hector", "hector@gmail.com"),
                    new Usuario("Ingrid", "ingrid@gmail.com"),
                    new Usuario("Joaquin", "joaquin@gmail.com"),
                    new Usuario("Karina", "karina@gmail.com"),
                    new Usuario("Leonardo", "leonardo@gmail.com"),
                    new Usuario("Monica", "monica@gmail.com"),
                    new Usuario("Nicolas", "nicolas@gmail.com"),
                    new Usuario("Olivia", "olivia@gmail.com"),
                    new Usuario("Pilar", "pilar@gmail.com"),
                    new Usuario("Quentin", "quentin@gmail.com"),
                    new Usuario("Raquel", "raquel2@gmail.com"),
                    new Usuario("Samuel", "samuel@gmail.com"),
                    new Usuario("Teresa", "teresa2@gmail.com"),
                    new Usuario("Ursula", "ursula@gmail.com"),
                    new Usuario("Victoriano", "victoriano@gmail.com"),
                    new Usuario("Wanda", "wanda@gmail.com"),
                    new Usuario("Ximena", "ximena@gmail.com"),
                    new Usuario("Yolanda", "yolanda@gmail.com"),
                    new Usuario("Zoe", "zoe@gmail.com"),
                    new Usuario("Andres", "andres2@gmail.com"),
                    new Usuario("Barbara", "barbara@gmail.com"),
                    new Usuario("Carlos", "carlos2@gmail.com"),
                    new Usuario("Diana", "diana@gmail.com"),
                    new Usuario("Elias", "elias@gmail.com"),
                    new Usuario("Fabiola", "fabiola@gmail.com"),
                    new Usuario("Gerardo", "gerardo@gmail.com"),
                    new Usuario("Hilda", "hilda@gmail.com"),
                    new Usuario("Ignacio", "ignacio@gmail.com"),
                    new Usuario("Jessica", "jessica@gmail.com"),
                    new Usuario("Karla", "karla@gmail.com"),
                    new Usuario("Luis", "luis3@gmail.com"),
                    new Usuario("Matias", "matias@gmail.com"),
                    new Usuario("Noelia", "noelia@gmail.com"),
                    new Usuario("Octavio", "octavio@gmail.com"),
                    new Usuario("Patricia", "patricia2@gmail.com"),
                    new Usuario("Quirino", "quirino@gmail.com"),
                    new Usuario("Ricardo", "ricardo@gmail.com"),
                    new Usuario("Silvia", "silvia@gmail.com"),
                    new Usuario("Tomas", "tomas2@gmail.com"),
                    new Usuario("Ubaldo", "ubaldo@gmail.com"),
                    new Usuario("Valeria", "valeria@gmail.com"),
                    new Usuario("Walter", "walter@gmail.com"),
                    new Usuario("Xavier", "xavier@gmail.com"),
                    new Usuario("Yasmín", "yasmin@gmail.com"),
                    new Usuario("Zulema", "zulema@gmail.com"),
                    new Usuario("Alba", "alba@gmail.com"),
                    new Usuario("Bruno", "bruno@gmail.com"),
                    new Usuario("Cecilia", "cecilia@gmail.com"),
                    new Usuario("Diego", "diego2@gmail.com"),
                    new Usuario("Estela", "estela@gmail.com"),
                    new Usuario("Felipe", "felipe2@gmail.com"),
                    new Usuario("Graciela", "graciela@gmail.com"),
                    new Usuario("Hugo", "hugo@gmail.com"),
                    new Usuario("Isidro", "isidro@gmail.com"),
                    new Usuario("Jasmine", "jasmine@gmail.com"),
                    new Usuario("Kendall", "kendall@gmail.com"),
                    new Usuario("Lia", "lia@gmail.com"),
                    new Usuario("Manuel", "manuel@gmail.com"),
                    new Usuario("Nina", "nina@gmail.com"),
                    new Usuario("Omar", "omar@gmail.com"),
                    new Usuario("Paloma", "paloma@gmail.com"),
                    new Usuario("Quiana", "quiana@gmail.com"),
                    new Usuario("Rebeca", "rebeca@gmail.com"),
                    new Usuario("Santiago", "santiago@gmail.com"),
                    new Usuario("Talia", "talia@gmail.com"),
                    new Usuario("Uriah", "uriah@gmail.com"),
                    new Usuario("Vanessa", "vanessa@gmail.com"),
                    new Usuario("Wilma", "wilma@gmail.com"),
                    new Usuario("Xena", "xena@gmail.com"),
                    new Usuario("Yara", "yara@gmail.com"),
                    new Usuario("Zara", "zara@gmail.com")
                    );

            usuarioRepository.saveAll(usuarios);
        };
    }

}
